
workflows:
  my-workflow:
    scripts:
      - name: Launch emulator
        script: |
          set -e # exit on first failed command
          cd $ANDROID_HOME/tools
          emulator -avd emulator &
          adb wait-for-device
    
        script: |
          set -e # exit on first failed command
          echo ${GCODE_base64?} > ./gcloud_key_file.json
          gcloud auth activate-service-account --key-file=gcloud_key_file.json
          gcloud --quiet config set project ${FIREBASE_PROJECT}
      
        script: |
          set -e # exit on first failed command

          gcloud firebase test --help
        
        script: ./gradlew test
        test_report: app/build/**/*.xml

  